# this is geoinsight options(2024-12-01)

PPP_Glo.RT_flag   =1    #0:POST 1:Real-time


# input stream
# strtype[0]        =2    # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripcli,7:ftp,8:http)
strtype[0]        =6    # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripcli,7:ftp,8:http)
strtype[1]        =6    # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripcli,7:ftp,8:http)
# strfmt[0]         =1    # (0:rtcm2,1:rtcm3,2:oem4,3:oem3,4:ubx,5:ss2,6:hemis,7:skytraq,20:sino,21:unicore,14:sp3)
strfmt[0]         =20    # (0:rtcm2,1:rtcm3,2:oem4,3:oem3,4:ubx,5:ss2,6:hemis,7:skytraq,20:sino,21:unicore,14:sp3)
strfmt[1]         =20    # (0:rtcm2,1:rtcm3,2:oem4,3:oem3,4:ubx,5:ss2,6:hemis,7:skytraq,20:sino,21:unicore,14:sp3)
# strpath[0]        =/home/book/GNSS/GNSS_DataSet/20241129B2b/sinan/0222/Rov_202503020000.log::T::x5
strpath[0]        =user2:pass2@1.94.195.74:2101/SINO_B2b
strpath[1]        =user2:pass2@1.94.195.74:2101/SINO_Nav

# log stream
# strtype[5]        =2    # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripcli,7:ftp,8:http)
strtype[5]        =2    # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripcli,7:ftp,8:http)
strtype[6]        =2    # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripcli,7:ftp,8:http)
# strpath[5]        =./Rov_%Y%m%d%h%M.log::T::S=24     #
strpath[5]        =/home/pi/workspace/dataset/rtdecoder/Bas_%Y%m%d%h%M.log::T::S=24     #
strpath[6]        =/home/pi/workspace/dataset/rtdecoder/Cor_%Y%m%d%h%M.log::T::S=24     #

# misc option
svrcycle          =10    # (ms)
timeout           =10000 # (ms)
reconnect         =10000 # (ms)
nmeacycle         =5000  # (ms)
buffsize          =32768 # (bytes)
